// This file is generated by rust-protobuf 2.28.0. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `common-index-format-v1.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_28_0;

#[derive(PartialEq,Clone,Default)]
pub struct Header {
    // message fields
    pub version: i32,
    pub num_postings_lists: i32,
    pub num_docs: i32,
    pub total_postings_lists: i32,
    pub total_docs: i32,
    pub total_terms_in_collection: i64,
    pub average_doclength: f64,
    pub description: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Header {
    fn default() -> &'a Header {
        <Header as ::protobuf::Message>::default_instance()
    }
}

impl Header {
    pub fn new() -> Header {
        ::std::default::Default::default()
    }

    // int32 version = 1;


    pub fn get_version(&self) -> i32 {
        self.version
    }
    pub fn clear_version(&mut self) {
        self.version = 0;
    }

    // Param is passed by value, moved
    pub fn set_version(&mut self, v: i32) {
        self.version = v;
    }

    // int32 num_postings_lists = 2;


    pub fn get_num_postings_lists(&self) -> i32 {
        self.num_postings_lists
    }
    pub fn clear_num_postings_lists(&mut self) {
        self.num_postings_lists = 0;
    }

    // Param is passed by value, moved
    pub fn set_num_postings_lists(&mut self, v: i32) {
        self.num_postings_lists = v;
    }

    // int32 num_docs = 3;


    pub fn get_num_docs(&self) -> i32 {
        self.num_docs
    }
    pub fn clear_num_docs(&mut self) {
        self.num_docs = 0;
    }

    // Param is passed by value, moved
    pub fn set_num_docs(&mut self, v: i32) {
        self.num_docs = v;
    }

    // int32 total_postings_lists = 4;


    pub fn get_total_postings_lists(&self) -> i32 {
        self.total_postings_lists
    }
    pub fn clear_total_postings_lists(&mut self) {
        self.total_postings_lists = 0;
    }

    // Param is passed by value, moved
    pub fn set_total_postings_lists(&mut self, v: i32) {
        self.total_postings_lists = v;
    }

    // int32 total_docs = 5;


    pub fn get_total_docs(&self) -> i32 {
        self.total_docs
    }
    pub fn clear_total_docs(&mut self) {
        self.total_docs = 0;
    }

    // Param is passed by value, moved
    pub fn set_total_docs(&mut self, v: i32) {
        self.total_docs = v;
    }

    // int64 total_terms_in_collection = 6;


    pub fn get_total_terms_in_collection(&self) -> i64 {
        self.total_terms_in_collection
    }
    pub fn clear_total_terms_in_collection(&mut self) {
        self.total_terms_in_collection = 0;
    }

    // Param is passed by value, moved
    pub fn set_total_terms_in_collection(&mut self, v: i64) {
        self.total_terms_in_collection = v;
    }

    // double average_doclength = 7;


    pub fn get_average_doclength(&self) -> f64 {
        self.average_doclength
    }
    pub fn clear_average_doclength(&mut self) {
        self.average_doclength = 0.;
    }

    // Param is passed by value, moved
    pub fn set_average_doclength(&mut self, v: f64) {
        self.average_doclength = v;
    }

    // string description = 8;


    pub fn get_description(&self) -> &str {
        &self.description
    }
    pub fn clear_description(&mut self) {
        self.description.clear();
    }

    // Param is passed by value, moved
    pub fn set_description(&mut self, v: ::std::string::String) {
        self.description = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_description(&mut self) -> &mut ::std::string::String {
        &mut self.description
    }

    // Take field
    pub fn take_description(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.description, ::std::string::String::new())
    }
}

impl ::protobuf::Message for Header {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.version = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.num_postings_lists = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.num_docs = tmp;
                },
                4 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.total_postings_lists = tmp;
                },
                5 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.total_docs = tmp;
                },
                6 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.total_terms_in_collection = tmp;
                },
                7 => {
                    if wire_type != ::protobuf::wire_format::WireTypeFixed64 {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_double()?;
                    self.average_doclength = tmp;
                },
                8 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.description)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.version != 0 {
            my_size += ::protobuf::rt::value_size(1, self.version, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.num_postings_lists != 0 {
            my_size += ::protobuf::rt::value_size(2, self.num_postings_lists, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.num_docs != 0 {
            my_size += ::protobuf::rt::value_size(3, self.num_docs, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.total_postings_lists != 0 {
            my_size += ::protobuf::rt::value_size(4, self.total_postings_lists, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.total_docs != 0 {
            my_size += ::protobuf::rt::value_size(5, self.total_docs, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.total_terms_in_collection != 0 {
            my_size += ::protobuf::rt::value_size(6, self.total_terms_in_collection, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.average_doclength != 0. {
            my_size += 9;
        }
        if !self.description.is_empty() {
            my_size += ::protobuf::rt::string_size(8, &self.description);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.version != 0 {
            os.write_int32(1, self.version)?;
        }
        if self.num_postings_lists != 0 {
            os.write_int32(2, self.num_postings_lists)?;
        }
        if self.num_docs != 0 {
            os.write_int32(3, self.num_docs)?;
        }
        if self.total_postings_lists != 0 {
            os.write_int32(4, self.total_postings_lists)?;
        }
        if self.total_docs != 0 {
            os.write_int32(5, self.total_docs)?;
        }
        if self.total_terms_in_collection != 0 {
            os.write_int64(6, self.total_terms_in_collection)?;
        }
        if self.average_doclength != 0. {
            os.write_double(7, self.average_doclength)?;
        }
        if !self.description.is_empty() {
            os.write_string(8, &self.description)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Header {
        Header::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "version",
                |m: &Header| { &m.version },
                |m: &mut Header| { &mut m.version },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "num_postings_lists",
                |m: &Header| { &m.num_postings_lists },
                |m: &mut Header| { &mut m.num_postings_lists },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "num_docs",
                |m: &Header| { &m.num_docs },
                |m: &mut Header| { &mut m.num_docs },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "total_postings_lists",
                |m: &Header| { &m.total_postings_lists },
                |m: &mut Header| { &mut m.total_postings_lists },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "total_docs",
                |m: &Header| { &m.total_docs },
                |m: &mut Header| { &mut m.total_docs },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "total_terms_in_collection",
                |m: &Header| { &m.total_terms_in_collection },
                |m: &mut Header| { &mut m.total_terms_in_collection },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeDouble>(
                "average_doclength",
                |m: &Header| { &m.average_doclength },
                |m: &mut Header| { &mut m.average_doclength },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "description",
                |m: &Header| { &m.description },
                |m: &mut Header| { &mut m.description },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Header>(
                "Header",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Header {
        static instance: ::protobuf::rt::LazyV2<Header> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Header::new)
    }
}

impl ::protobuf::Clear for Header {
    fn clear(&mut self) {
        self.version = 0;
        self.num_postings_lists = 0;
        self.num_docs = 0;
        self.total_postings_lists = 0;
        self.total_docs = 0;
        self.total_terms_in_collection = 0;
        self.average_doclength = 0.;
        self.description.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Header {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Header {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct Posting {
    // message fields
    pub docid: i32,
    pub tf: i32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a Posting {
    fn default() -> &'a Posting {
        <Posting as ::protobuf::Message>::default_instance()
    }
}

impl Posting {
    pub fn new() -> Posting {
        ::std::default::Default::default()
    }

    // int32 docid = 1;


    pub fn get_docid(&self) -> i32 {
        self.docid
    }
    pub fn clear_docid(&mut self) {
        self.docid = 0;
    }

    // Param is passed by value, moved
    pub fn set_docid(&mut self, v: i32) {
        self.docid = v;
    }

    // int32 tf = 2;


    pub fn get_tf(&self) -> i32 {
        self.tf
    }
    pub fn clear_tf(&mut self) {
        self.tf = 0;
    }

    // Param is passed by value, moved
    pub fn set_tf(&mut self, v: i32) {
        self.tf = v;
    }
}

impl ::protobuf::Message for Posting {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.docid = tmp;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.tf = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.docid != 0 {
            my_size += ::protobuf::rt::value_size(1, self.docid, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.tf != 0 {
            my_size += ::protobuf::rt::value_size(2, self.tf, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.docid != 0 {
            os.write_int32(1, self.docid)?;
        }
        if self.tf != 0 {
            os.write_int32(2, self.tf)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> Posting {
        Posting::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "docid",
                |m: &Posting| { &m.docid },
                |m: &mut Posting| { &mut m.docid },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "tf",
                |m: &Posting| { &m.tf },
                |m: &mut Posting| { &mut m.tf },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<Posting>(
                "Posting",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static Posting {
        static instance: ::protobuf::rt::LazyV2<Posting> = ::protobuf::rt::LazyV2::INIT;
        instance.get(Posting::new)
    }
}

impl ::protobuf::Clear for Posting {
    fn clear(&mut self) {
        self.docid = 0;
        self.tf = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for Posting {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for Posting {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct PostingsList {
    // message fields
    pub term: ::std::string::String,
    pub df: i64,
    pub cf: i64,
    pub postings: ::protobuf::RepeatedField<Posting>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a PostingsList {
    fn default() -> &'a PostingsList {
        <PostingsList as ::protobuf::Message>::default_instance()
    }
}

impl PostingsList {
    pub fn new() -> PostingsList {
        ::std::default::Default::default()
    }

    // string term = 1;


    pub fn get_term(&self) -> &str {
        &self.term
    }
    pub fn clear_term(&mut self) {
        self.term.clear();
    }

    // Param is passed by value, moved
    pub fn set_term(&mut self, v: ::std::string::String) {
        self.term = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_term(&mut self) -> &mut ::std::string::String {
        &mut self.term
    }

    // Take field
    pub fn take_term(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.term, ::std::string::String::new())
    }

    // int64 df = 2;


    pub fn get_df(&self) -> i64 {
        self.df
    }
    pub fn clear_df(&mut self) {
        self.df = 0;
    }

    // Param is passed by value, moved
    pub fn set_df(&mut self, v: i64) {
        self.df = v;
    }

    // int64 cf = 3;


    pub fn get_cf(&self) -> i64 {
        self.cf
    }
    pub fn clear_cf(&mut self) {
        self.cf = 0;
    }

    // Param is passed by value, moved
    pub fn set_cf(&mut self, v: i64) {
        self.cf = v;
    }

    // repeated .Posting postings = 4;


    pub fn get_postings(&self) -> &[Posting] {
        &self.postings
    }
    pub fn clear_postings(&mut self) {
        self.postings.clear();
    }

    // Param is passed by value, moved
    pub fn set_postings(&mut self, v: ::protobuf::RepeatedField<Posting>) {
        self.postings = v;
    }

    // Mutable pointer to the field.
    pub fn mut_postings(&mut self) -> &mut ::protobuf::RepeatedField<Posting> {
        &mut self.postings
    }

    // Take field
    pub fn take_postings(&mut self) -> ::protobuf::RepeatedField<Posting> {
        ::std::mem::replace(&mut self.postings, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for PostingsList {
    fn is_initialized(&self) -> bool {
        for v in &self.postings {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.term)?;
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.df = tmp;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int64()?;
                    self.cf = tmp;
                },
                4 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.postings)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if !self.term.is_empty() {
            my_size += ::protobuf::rt::string_size(1, &self.term);
        }
        if self.df != 0 {
            my_size += ::protobuf::rt::value_size(2, self.df, ::protobuf::wire_format::WireTypeVarint);
        }
        if self.cf != 0 {
            my_size += ::protobuf::rt::value_size(3, self.cf, ::protobuf::wire_format::WireTypeVarint);
        }
        for value in &self.postings {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if !self.term.is_empty() {
            os.write_string(1, &self.term)?;
        }
        if self.df != 0 {
            os.write_int64(2, self.df)?;
        }
        if self.cf != 0 {
            os.write_int64(3, self.cf)?;
        }
        for v in &self.postings {
            os.write_tag(4, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> PostingsList {
        PostingsList::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "term",
                |m: &PostingsList| { &m.term },
                |m: &mut PostingsList| { &mut m.term },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "df",
                |m: &PostingsList| { &m.df },
                |m: &mut PostingsList| { &mut m.df },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt64>(
                "cf",
                |m: &PostingsList| { &m.cf },
                |m: &mut PostingsList| { &mut m.cf },
            ));
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<Posting>>(
                "postings",
                |m: &PostingsList| { &m.postings },
                |m: &mut PostingsList| { &mut m.postings },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<PostingsList>(
                "PostingsList",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static PostingsList {
        static instance: ::protobuf::rt::LazyV2<PostingsList> = ::protobuf::rt::LazyV2::INIT;
        instance.get(PostingsList::new)
    }
}

impl ::protobuf::Clear for PostingsList {
    fn clear(&mut self) {
        self.term.clear();
        self.df = 0;
        self.cf = 0;
        self.postings.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for PostingsList {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for PostingsList {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct DocRecord {
    // message fields
    pub docid: i32,
    pub collection_docid: ::std::string::String,
    pub doclength: i32,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a DocRecord {
    fn default() -> &'a DocRecord {
        <DocRecord as ::protobuf::Message>::default_instance()
    }
}

impl DocRecord {
    pub fn new() -> DocRecord {
        ::std::default::Default::default()
    }

    // int32 docid = 1;


    pub fn get_docid(&self) -> i32 {
        self.docid
    }
    pub fn clear_docid(&mut self) {
        self.docid = 0;
    }

    // Param is passed by value, moved
    pub fn set_docid(&mut self, v: i32) {
        self.docid = v;
    }

    // string collection_docid = 2;


    pub fn get_collection_docid(&self) -> &str {
        &self.collection_docid
    }
    pub fn clear_collection_docid(&mut self) {
        self.collection_docid.clear();
    }

    // Param is passed by value, moved
    pub fn set_collection_docid(&mut self, v: ::std::string::String) {
        self.collection_docid = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_collection_docid(&mut self) -> &mut ::std::string::String {
        &mut self.collection_docid
    }

    // Take field
    pub fn take_collection_docid(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.collection_docid, ::std::string::String::new())
    }

    // int32 doclength = 3;


    pub fn get_doclength(&self) -> i32 {
        self.doclength
    }
    pub fn clear_doclength(&mut self) {
        self.doclength = 0;
    }

    // Param is passed by value, moved
    pub fn set_doclength(&mut self, v: i32) {
        self.doclength = v;
    }
}

impl ::protobuf::Message for DocRecord {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.docid = tmp;
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.collection_docid)?;
                },
                3 => {
                    if wire_type != ::protobuf::wire_format::WireTypeVarint {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    let tmp = is.read_int32()?;
                    self.doclength = tmp;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.docid != 0 {
            my_size += ::protobuf::rt::value_size(1, self.docid, ::protobuf::wire_format::WireTypeVarint);
        }
        if !self.collection_docid.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.collection_docid);
        }
        if self.doclength != 0 {
            my_size += ::protobuf::rt::value_size(3, self.doclength, ::protobuf::wire_format::WireTypeVarint);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        if self.docid != 0 {
            os.write_int32(1, self.docid)?;
        }
        if !self.collection_docid.is_empty() {
            os.write_string(2, &self.collection_docid)?;
        }
        if self.doclength != 0 {
            os.write_int32(3, self.doclength)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> DocRecord {
        DocRecord::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "docid",
                |m: &DocRecord| { &m.docid },
                |m: &mut DocRecord| { &mut m.docid },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                "collection_docid",
                |m: &DocRecord| { &m.collection_docid },
                |m: &mut DocRecord| { &mut m.collection_docid },
            ));
            fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeInt32>(
                "doclength",
                |m: &DocRecord| { &m.doclength },
                |m: &mut DocRecord| { &mut m.doclength },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<DocRecord>(
                "DocRecord",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static DocRecord {
        static instance: ::protobuf::rt::LazyV2<DocRecord> = ::protobuf::rt::LazyV2::INIT;
        instance.get(DocRecord::new)
    }
}

impl ::protobuf::Clear for DocRecord {
    fn clear(&mut self) {
        self.docid = 0;
        self.collection_docid.clear();
        self.doclength = 0;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for DocRecord {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for DocRecord {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n\x1ccommon-index-format-v1.proto\"\xd8\x02\n\x06Header\x12\x1a\n\x07ve\
    rsion\x18\x01\x20\x01(\x05R\x07versionB\0\x12.\n\x12num_postings_lists\
    \x18\x02\x20\x01(\x05R\x10numPostingsListsB\0\x12\x1b\n\x08num_docs\x18\
    \x03\x20\x01(\x05R\x07numDocsB\0\x122\n\x14total_postings_lists\x18\x04\
    \x20\x01(\x05R\x12totalPostingsListsB\0\x12\x1f\n\ntotal_docs\x18\x05\
    \x20\x01(\x05R\ttotalDocsB\0\x12;\n\x19total_terms_in_collection\x18\x06\
    \x20\x01(\x03R\x16totalTermsInCollectionB\0\x12-\n\x11average_doclength\
    \x18\x07\x20\x01(\x01R\x10averageDoclengthB\0\x12\"\n\x0bdescription\x18\
    \x08\x20\x01(\tR\x0bdescriptionB\0:\0\"5\n\x07Posting\x12\x16\n\x05docid\
    \x18\x01\x20\x01(\x05R\x05docidB\0\x12\x10\n\x02tf\x18\x02\x20\x01(\x05R\
    \x02tfB\0:\0\"r\n\x0cPostingsList\x12\x14\n\x04term\x18\x01\x20\x01(\tR\
    \x04termB\0\x12\x10\n\x02df\x18\x02\x20\x01(\x03R\x02dfB\0\x12\x10\n\x02\
    cf\x18\x03\x20\x01(\x03R\x02cfB\0\x12&\n\x08postings\x18\x04\x20\x03(\
    \x0b2\x08.PostingR\x08postingsB\0:\0\"r\n\tDocRecord\x12\x16\n\x05docid\
    \x18\x01\x20\x01(\x05R\x05docidB\0\x12+\n\x10collection_docid\x18\x02\
    \x20\x01(\tR\x0fcollectionDocidB\0\x12\x1e\n\tdoclength\x18\x03\x20\x01(\
    \x05R\tdoclengthB\0:\0B\0b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
